---
title: "Prediction Template"
output: html_notebook
---

Hopefully this can serve as a guide to using the package with this selection of data.

First to install the package.
```{r}
library(readr)
library(stringr)
library(devtools)
if (!require(robencla)) {
  devtools::install_github("https://github.com/Gibbsdavidl/robencla",quiet = TRUE)
}
```


Then we need to read in the training data.

```{r}

## EDIT THIS ##
data_dir <- 'F:/Work/cluster_prediction_data/'

# The immune subtypes### Use: ClusterModel1 as the subtype
subtypes <- readr::read_delim(paste0(data_dir,'data/five_signature_mclust_ensemble_results.tsv.gz'), delim = '\t')
subtypes$AliquotBarcode <- str_replace_all(string = subtypes$AliquotBarcode, pattern = '\\.', replacement = '-')
subtypes$SampleBarcode2 <- str_sub(subtypes$SampleBarcode, start = 1, end = 15)
subtypes$SampleBarcode2 <- str_sub(subtypes$SampleBarcode, start = 1, end = 15)

# The Pan-Cancer EB++ (named EBpp) batch corrected data set
ebpp <- readr::read_delim(paste0(data_dir,'data/EBpp/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv'),delim = '\t')
ebpp$gene_id <- NULL

ebpp_genes <- readr::read_csv(paste0(data_dir,'data/EBpp/ebpp_genes.txt'))
gene_symbols <- unlist(sapply(
  sapply(ebpp_genes, function(x) str_split(x,pattern='\\|')),
    function(y) y[[1]]
    ))

idx <- which( gene_symbols != '?' )
ebpp <- ebpp[idx,]
rownames(ebpp) <- gene_symbols[idx]

ebpp <- ebpp[, subtypes$aliquots]
```

Then we'll pick a random set of genes.
```{r}
jdx <- sample.int(20520,size=88,FALSE)

ebpp_sub <- ebpp[jdx,]

```



The end.